name: Publish release

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Setting version to ') && !contains(github.event.head_commit.message, 'SNAPSHOT')"
    steps:
      - name: Extract version from commit message
        run: |
          version=${COMMIT_MSG#"Setting version to "}
          echo "::set-env name=VERSION::$version"
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          version: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}